name = "PhotonicSystemChannels"
authors = ["Paul Virally <pvirally@gmail.com>"]

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GilaElectromagnetics = "d021e48d-d5bb-41e2-b1a9-c560019218de"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
MatrixFreeRandomizedLinearAlgebra = "a69accfa-5557-4533-9d8b-afe141969680"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[sources]
GilaElectromagnetics = {rev = "paul-gila-operators", url = "https://github.com/PaulVirally/GilaElectromagnetics.jl/"}
